notifications:
  email: false

language: go

go:
  - "1.10"

script:
  - go test -cover -tags="integration unit" | tee cover.out
  - coverage_pct=$(awk '$1 == "coverage:" {print $2}' cover.out)
  - echo $coverage_pct